import {
  Cog,
  Factory,
  Flame,
  Hammer,
  ShieldCheck,
  Truck,
  Wrench,
} from 'lucide-react';

const serviceImages = [
  '/images/company/tjader-welding.png',
  '/images/company/structural-steel-installation.jpeg',
  '/images/company/welder-at-industrial-machine.png',
  '/images/company/on-site-trailer-repair.jpeg',
  '/images/company/industrial-welding-equipment.jpeg',
  '/images/company/welder-at-industrial-machine.png',
];

export const publicServices = [
  {
    title: 'Welding',
    path: '/services/welding',
    summary: 'Reliable welding for industrial equipment, structures and repairs.',
    description: 'Professional welding for industrial work where sound preparation, the right process and dependable workmanship matter. We work on site or in the workshop to help keep equipment and steelwork safe, strong and productive.',
    included: ['Industrial and structural welding', 'Repair and modification work', 'On-site assessment and preparation', 'Careful finishing and quality checks'],
    images: [serviceImages[0], serviceImages[2], serviceImages[4]],
    icon: Flame,
  },
  {
    title: 'Industrial Fabrication',
    path: '/services/industrial-fabrication',
    summary: 'Purpose-built metal components and assemblies for demanding work.',
    description: 'From a single component to a complete assembly, industrial fabrication is planned around how the finished work will be used. We combine practical workshop skills with clear communication and attention to fit, function and finish.',
    included: ['Component and assembly fabrication', 'Cutting, fitting and welding', 'Repair and improvement of existing fabrications', 'Workshop and site coordination'],
    images: [serviceImages[1], serviceImages[4], serviceImages[5]],
    icon: Factory,
  },
  {
    title: 'Field Welding',
    path: '/services/field-welding',
    summary: 'Mobile welding support at your facility, project or remote worksite.',
    description: 'When work cannot wait for equipment to reach a workshop, our field welding service brings skilled support and practical tools directly to your site. We assess the task, coordinate access and carry out the work with safety and uptime in mind.',
    included: ['On-site welding and repair', 'Mobile service across Sweden', 'Worksite planning and safe setup', 'Practical support for urgent jobs'],
    images: [serviceImages[2], serviceImages[0], '/images/company/field-service-site-overview.jpeg'],
    icon: Truck,
  },
  {
    title: 'Maintenance & Repairs',
    path: '/services/maintenance-repairs',
    summary: 'Practical repairs and maintenance to keep industrial equipment working.',
    description: 'Planned maintenance and responsive repair work help extend service life and reduce unnecessary downtime. We investigate the issue, agree on the best way forward and complete durable repairs suited to the working environment.',
    included: ['Equipment inspection and repair', 'Weld repairs and reinforcement', 'Modifications and improvements', 'Maintenance support at your site'],
    images: [serviceImages[3], serviceImages[2], serviceImages[4]],
    icon: Wrench,
  },
  {
    title: 'Steel & Metalwork',
    path: '/services/steel-metalwork',
    summary: 'Carefully executed steelwork and metal fabrication for industry.',
    description: 'We deliver practical steel and metalwork for demanding environments, from fabrication through installation. Every job is coordinated around site conditions, safe handling and the details that make the finished work perform reliably.',
    included: ['Steel and metal fabrication', 'Structural repairs and reinforcement', 'Site installation and fitting', 'Finishing and final checks'],
    images: [serviceImages[4], serviceImages[1], serviceImages[0]],
    icon: Hammer,
  },
  {
    title: 'Custom Fabrication',
    path: '/services/custom-fabrication',
    summary: 'Flexible, made-to-measure fabrication shaped around your requirements.',
    description: 'For unique requirements, we work with you to turn a practical need into a well-made solution. We consider the intended use, materials, site conditions and schedule, then fabricate to fit the job rather than forcing a standard answer.',
    included: ['Made-to-measure components', 'One-off builds and prototypes', 'Design and material coordination', 'Fabrication, fitting and refinement'],
    images: [serviceImages[5], serviceImages[1], serviceImages[3]],
    icon: Cog,
  },
];

export const publicProjects = [
  {
    title: 'Welding Projects',
    path: '/projects/welding-projects',
    summary: 'Industrial welding and repair work completed with care.',
    description: 'Welding projects call for sound preparation, capable execution and an understanding of the conditions the finished work must withstand. We support industrial customers with repairs, site welding and fabrication work built for real-world use.',
    included: ['Industrial welding', 'On-site repair work', 'Steel preparation and fitting', 'Finishing and quality checks'],
    images: [serviceImages[0], serviceImages[2], serviceImages[4]],
    icon: Flame,
  },
  {
    title: 'Fabrication Projects',
    path: '/projects/fabrication-projects',
    summary: 'Custom components, assemblies and practical metalwork.',
    description: 'Our fabrication projects range from individual parts to larger assemblies. We plan around the application, coordinate materials and deliver carefully fabricated work that is ready for installation or immediate use.',
    included: ['Custom metal fabrication', 'Components and assemblies', 'Workshop welding and fitting', 'Installation-ready delivery'],
    images: [serviceImages[1], serviceImages[5], serviceImages[0]],
    icon: Factory,
  },
  {
    title: 'Industrial Projects',
    path: '/projects/industrial-projects',
    summary: 'Hands-on welding and fabrication for active industrial sites.',
    description: 'Industrial projects often involve tight schedules, live operations and demanding site conditions. We bring practical experience, clear coordination and dependable workmanship to each stage of the job.',
    included: ['Site welding and fabrication', 'Maintenance and repair work', 'Worksite coordination', 'Safe, reliable delivery'],
    images: [serviceImages[4], serviceImages[2], '/images/company/industrial-site-team.jpeg'],
    icon: ShieldCheck,
  },
  {
    title: 'Machine & Equipment Projects',
    path: '/projects/machine-equipment-projects',
    summary: 'Repair, reinforcement and modifications for industrial equipment.',
    description: 'We help maintain the equipment that keeps operations moving. From damaged parts to practical upgrades, our machine and equipment projects focus on restoring function and delivering robust work suited to the machine’s environment.',
    included: ['Machine and equipment repairs', 'Welded reinforcement', 'Modifications and upgrades', 'On-site service and fitting'],
    images: [serviceImages[2], serviceImages[3], serviceImages[4]],
    icon: Wrench,
  },
  {
    title: 'Steel Structure Projects',
    path: '/projects/steel-structure-projects',
    summary: 'Steel installation, structural fabrication and site fitting.',
    description: 'Steel structure projects depend on accurate fabrication, careful handling and a safe, coordinated installation. We support structural work from preparation and fitting through welding and final checks.',
    included: ['Structural steel fabrication', 'Site fitting and installation', 'Welding and reinforcement', 'Safe work planning and final checks'],
    images: [serviceImages[1], serviceImages[4], '/images/company/industrial-site-team.jpeg'],
    icon: Hammer,
  },
  {
    title: 'Field Service Projects',
    path: '/projects/field-service-projects',
    summary: 'Mobile welding, maintenance and repair wherever work is needed.',
    description: 'Our field service projects take practical welding and technical support directly to customer facilities and project sites across Sweden. We arrive prepared, coordinate with your team and focus on getting the work completed reliably.',
    included: ['Mobile welding and repairs', 'On-site maintenance support', 'Service vehicle and job preparation', 'Nationwide project response'],
    images: ['/images/company/field-service-site-overview.jpeg', '/images/company/field-service-vehicle-site.jpeg', serviceImages[2]],
    icon: Truck,
  },
];
